export {
  defineResource,
  type ResourceConfig,
  type NavigationConfig,
  type TableConfig,
  type FormConfig,
  type ColumnDefinition,
  type FieldDefinition,
  type FilterDefinition,
  type ActionDefinition,
  type FormLayout,
  type NextPanelActions,
  type QueryOptions,
  type QueryResult,
} from "./types";
